### ISSUE TITLE
[[WinRM::FS::Core::FileTransporter] Upload failed (exitcode: 0), but stderr present

### ISSUE THREAD

**Issue by MattHodge** [test-kitchen/kitchen-dsc#20]
Getting error `[[WinRM::FS::Core::FileTransporter] Upload failed (exitcode: 0), but stderr present` when using the vagrant driver.

Windows 2016 Core TP5

Debug Log:
```
-----> Starting Kitchen (v1.10.0)
D      [Vagrant command] BEGIN (vagrant --version)
D      [Vagrant command] END (0m0.00s)
D      [Vagrant command] BEGIN (vagrant plugin list)
D      [Vagrant command] END (0m0.00s)
D      winrm requested, loading winrm gem (["~> 1.6"])
D      winrm is loaded.
D      winrm-fs requested, loading winrm-fs gem (["~> 0.4.1"])
D      winrm-fs is loaded.
-----> Converging <default-Win2016TP5Core>...
       Preparing files for transfer
D      Creating local sandbox in C:/Users/M3A3E~1.HOD/AppData/Local/Temp/default-Win2016TP5Core-sandbox-20160618-14804-1j2dr2l
       Staging DSC Resource Modules for copy to the SUT
D      Enumerating C:/ProjectsGit/Hubot/build.ps1
D      Enumerating C:/ProjectsGit/Hubot/DSCResources
D      Enumerating C:/ProjectsGit/Hubot/Examples
D      Enumerating C:/ProjectsGit/Hubot/Hubot.psd1
D      Enumerating C:/ProjectsGit/Hubot/Hubot.psm1
D      Enumerating C:/ProjectsGit/Hubot/LICENSE
D      Enumerating C:/ProjectsGit/Hubot/README.md
D      Enumerating C:/ProjectsGit/Hubot/Tests
D      Enumerating C:/ProjectsGit/Hubot/DSCResources/HubotPrerequisites
D      Enumerating C:/ProjectsGit/Hubot/DSCResources/HubotPrerequisites/HubotPrerequisites.psd1
D      Enumerating C:/ProjectsGit/Hubot/DSCResources/HubotPrerequisites/HubotPrerequisites.schema.psm1
D      Enumerating C:/ProjectsGit/Hubot/Examples/dsc_configuration.ps1
D      Enumerating C:/ProjectsGit/Hubot/Tests/integration
D      Enumerating C:/ProjectsGit/Hubot/Tests/integration/default
D      Enumerating C:/ProjectsGit/Hubot/Tests/integration/default/pester
D      Enumerating C:/ProjectsGit/Hubot/Tests/integration/default/pester/default.tests.ps1
D      Enumerating C:/ProjectsGit/Hubot/Tests/unit
D      Enumerating C:/ProjectsGit/Hubot/Tests/unit/hubot.unit.tests.ps1
D      Staging C:/ProjectsGit/Hubot/build.ps1
D        at C:/Users/M3A3E~1.HOD/AppData/Local/Temp/default-Win2016TP5Core-sandbox-20160618-14804-1j2dr2l/modules/Hubot/build.ps1
D      Staging C:/ProjectsGit/Hubot/Hubot.psd1
D        at C:/Users/M3A3E~1.HOD/AppData/Local/Temp/default-Win2016TP5Core-sandbox-20160618-14804-1j2dr2l/modules/Hubot/Hubot.psd1
D      Staging C:/ProjectsGit/Hubot/Hubot.psm1
D        at C:/Users/M3A3E~1.HOD/AppData/Local/Temp/default-Win2016TP5Core-sandbox-20160618-14804-1j2dr2l/modules/Hubot/Hubot.psm1
D      Staging C:/ProjectsGit/Hubot/LICENSE
D        at C:/Users/M3A3E~1.HOD/AppData/Local/Temp/default-Win2016TP5Core-sandbox-20160618-14804-1j2dr2l/modules/Hubot/LICENSE
D      Staging C:/ProjectsGit/Hubot/DSCResources/HubotPrerequisites/HubotPrerequisites.psd1
D        at C:/Users/M3A3E~1.HOD/AppData/Local/Temp/default-Win2016TP5Core-sandbox-20160618-14804-1j2dr2l/modules/Hubot/DSCResources/HubotPrerequisites/HubotPrerequisites.psd1
D      Staging C:/ProjectsGit/Hubot/DSCResources/HubotPrerequisites/HubotPrerequisites.schema.psm1
D        at C:/Users/M3A3E~1.HOD/AppData/Local/Temp/default-Win2016TP5Core-sandbox-20160618-14804-1j2dr2l/modules/Hubot/DSCResources/HubotPrerequisites/HubotPrerequisites.schema.psm1
D      Staging C:/ProjectsGit/Hubot/Examples/dsc_configuration.ps1
D        at C:/Users/M3A3E~1.HOD/AppData/Local/Temp/default-Win2016TP5Core-sandbox-20160618-14804-1j2dr2l/modules/Hubot/Examples/dsc_configuration.ps1
D      Staging C:/ProjectsGit/Hubot/Tests/integration/default/pester/default.tests.ps1
D        at C:/Users/M3A3E~1.HOD/AppData/Local/Temp/default-Win2016TP5Core-sandbox-20160618-14804-1j2dr2l/modules/Hubot/Tests/integration/default/pester/default.tests.ps1
D      Staging C:/ProjectsGit/Hubot/Tests/unit/hubot.unit.tests.ps1
D        at C:/Users/M3A3E~1.HOD/AppData/Local/Temp/default-Win2016TP5Core-sandbox-20160618-14804-1j2dr2l/modules/Hubot/Tests/unit/hubot.unit.tests.ps1
       Staging DSC configuration script for copy to the SUT
D      Moving C:/ProjectsGit/Hubot/examples/dsc_configuration.ps1 to C:/Users/M3A3E~1.HOD/AppData/Local/Temp/default-Win2016TP5Core-sandbox-20160618-14804-1j2dr2l/configuration/dsc_configuration.ps1
D      [WinRM] negotiate::http://127.0.0.1:55985/wsman<{:user=>"vagrant", :pass=>"vagrant", :elevated_username=>"vagrant", :elevated_password=>"vagrant", :no_ssl_peer_verification=>true, :disable_sspi=>false, :basic_auth_only=>false}> (                    [DSCLocalConfigurationManager()]
            configuration SetupLCM
            {
              Settings
              {
                ActionAfterReboot = 'StopConfiguration'
                AllowModuleOverwrite = [bool]::Parse('true')
                CertificateID = '$null'
                ConfigurationMode = 'ApplyAndAutoCorrect'
                ConfigurationModeFrequencyMins = 15
                DebugMode = 'none'
                RebootNodeIfNeeded = [bool]::Parse('true')
                RefreshFrequencyMins = 30
                RefreshMode = 'PUSH'
              }
            }


        $null = SetupLCM
        Set-DscLocalConfigurationManager -Path ./SetupLCM | out-null
)
D      [WinRM] opening remote shell on http://127.0.0.1:55985/wsman
D      [WinRM] remote shell 4B853774-5DEF-4205-A743-13B4C25086B2 is open on http://127.0.0.1:55985/wsman
$$$$$$ #< CLIXML
$$$$$$ <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">2</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
       Bootstrapping the nuget package provider for PowerShell PackageManagement.
D      [WinRM] negotiate::http://127.0.0.1:55985/wsman<{:user=>"vagrant", :pass=>"vagrant", :elevated_username=>"vagrant", :elevated_password=>"vagrant", :no_ssl_peer_verification=>true, :disable_sspi=>false, :basic_auth_only=>false}> (mkdir (split-path (join-path $env:TEMP\kitchen configuration/dsc_configuration.ps1)) -force | out-null
  install-packageprovider nuget -force -forcebootstrap | out-null

  install-module -name 'cChoco' -Repository PSGallery -force | out-null
install-module -name 'xPSDesiredStateConfiguration' -Repository PSGallery -force | out-null

)
$$$$$$ #< CLIXML
$$$$$$ <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">2</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
       Transferring files to <default-Win2016TP5Core>
D      creating hash for directory $env:TEMP\kitchen
D      Populating files
D      +++ Adding dsc_configuration.ps1
D      === All files added.
D      creating hash for directory $env:TEMP\kitchen
D      Populating files
D      +++ Adding Hubot/DSCResources/HubotPrerequisites/HubotPrerequisites.psd1
D      +++ Adding Hubot/DSCResources/HubotPrerequisites/HubotPrerequisites.schema.psm1
D      +++ Adding Hubot/Examples/dsc_configuration.ps1
D      +++ Adding Hubot/Hubot.psd1
D      +++ Adding Hubot/Hubot.psm1
D      +++ Adding Hubot/LICENSE
D      +++ Adding Hubot/Tests/integration/default/pester/default.tests.ps1
D      +++ Adding Hubot/Tests/unit/hubot.unit.tests.ps1
D      +++ Adding Hubot/build.ps1
D      === All files added.
D      Running check_files.ps1
D      @{
D        "b3d56cc40accd1b4443bd6da0482a65a" = @{
D          "target" = "$env:TEMP\winrm-upload\tmpzip-b3d56cc40accd1b4443bd6da0482a65a.zip";
D          "src_basename" = "configuration";
D          "dst" = "$env:TEMP\kitchen\configuration"
D        };
D        "c78af2daf5f4c283e5dd8dbb5b9a4963" = @{
D          "target" = "$env:TEMP\winrm-upload\tmpzip-c78af2daf5f4c283e5dd8dbb5b9a4963.zip";
D          "src_basename" = "modules";
D          "dst" = "$env:TEMP\kitchen\modules"
D        }
D      }
D      Cleaning up local sandbox in C:/Users/M3A3E~1.HOD/AppData/Local/Temp/default-Win2016TP5Core-sandbox-20160618-14804-1j2dr2l
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #converge action: [[WinRM::FS::Core::FileTransporter] Upload failed (exitcode: 0), but stderr present
] on default-Win2016TP5Core
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: 1 actions failed.
>>>>>>     Failed to complete #converge action: [[WinRM::FS::Core::FileTransporter] Upload failed (exitcode: 0), but stderr present
] on default-Win2016TP5Core
D      ----------------------
D      ------Backtrace-------
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/command.rb:187:in `report_errors'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/command.rb:178:in `run_action'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/command/action.rb:39:in `block in call'
D      C:/opscode/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/command/action.rb:37:in `call'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/cli.rb:56:in `perform'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/cli.rb:184:in `block (2 levels) in <class:CLI>'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/cli.rb:325:in `invoke_task'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/bin/kitchen:13:in `block in <top (required)>'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/errors.rb:174:in `with_friendly_errors'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/bin/kitchen:13:in `<top (required)>'
D      C:/opscode/chefdk/bin/kitchen:20:in `load'
D      C:/opscode/chefdk/bin/kitchen:20:in `<main>'
D      ----End Backtrace-----
D      -Composite Exception--
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #converge action: [[WinRM::FS::Core::FileTransporter] Upload failed (exitcode: 0), but stderr present
] on default-Win2016TP5Core
D      ----------------------
D      ------Backtrace-------
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/winrm-fs-0.4.2/lib/winrm-fs/core/file_transporter.rb:397:in `parse_response'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/winrm-fs-0.4.2/lib/winrm-fs/core/file_transporter.rb:203:in `check_files'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/winrm-fs-0.4.2/lib/winrm-fs/core/file_transporter.rb:80:in `block in upload'
D      C:/opscode/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/winrm-fs-0.4.2/lib/winrm-fs/core/file_transporter.rb:78:in `upload'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/transport/winrm.rb:132:in `upload'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/provisioner/base.rb:75:in `block in call'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/transport/base.rb:94:in `initialize'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/transport/winrm.rb:468:in `new'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/transport/winrm.rb:468:in `create_new_connection'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/transport/winrm.rb:74:in `connection'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/provisioner/base.rb:71:in `call'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:373:in `block in converge_action'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:513:in `call'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:513:in `synchronize_or_call'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:478:in `block in action'
D      C:/opscode/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:477:in `action'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:369:in `converge_action'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:348:in `block in transition_to'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:347:in `each'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:347:in `transition_to'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:138:in `converge'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/command.rb:201:in `public_send'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/command.rb:201:in `run_action_in_thread'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/command.rb:173:in `block (2 levels) in run_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:450:in `call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:450:in `block in create_with_logging_context'
D      ----End Backtrace-----
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #converge action: [[WinRM::FS::Core::FileTransporter] Upload failed (exitcode: 0), but stderr present
]
D      ----------------------
D      ------Backtrace-------
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/winrm-fs-0.4.2/lib/winrm-fs/core/file_transporter.rb:397:in `parse_response'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/winrm-fs-0.4.2/lib/winrm-fs/core/file_transporter.rb:203:in `check_files'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/winrm-fs-0.4.2/lib/winrm-fs/core/file_transporter.rb:80:in `block in upload'
D      C:/opscode/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/winrm-fs-0.4.2/lib/winrm-fs/core/file_transporter.rb:78:in `upload'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/transport/winrm.rb:132:in `upload'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/provisioner/base.rb:75:in `block in call'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/transport/base.rb:94:in `initialize'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/transport/winrm.rb:468:in `new'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/transport/winrm.rb:468:in `create_new_connection'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/transport/winrm.rb:74:in `connection'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/provisioner/base.rb:71:in `call'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:373:in `block in converge_action'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:513:in `call'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:513:in `synchronize_or_call'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:478:in `block in action'
D      C:/opscode/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:477:in `action'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:369:in `converge_action'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:348:in `block in transition_to'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:347:in `each'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:347:in `transition_to'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:138:in `converge'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/command.rb:201:in `public_send'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/command.rb:201:in `run_action_in_thread'
D      C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/command.rb:173:in `block (2 levels) in run_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:450:in `call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:450:in `block in create_with_logging_context'
D      ----End Backtrace-----
D      [WinRM] closing remote shell 4B853774-5DEF-4205-A743-13B4C25086B2 on http://127.0.0.1:55985/wsman
D      [WinRM] remote shell 4B853774-5DEF-4205-A743-13B4C25086B2 closed
```

Kitchen Diagnose:
```yaml
---
timestamp: 2016-06-18 19:10:13 UTC
kitchen_version: 1.10.0
plugins:
  driver:
    Vagrant:
      class: Kitchen::Driver::Vagrant
      version: 0.20.0
      api_version: 2
  provisioner:
    Dsc:
      class: Kitchen::Provisioner::Dsc
      version:
      api_version: 2
  transport:
    Winrm:
      class: Kitchen::Transport::Winrm
      version: 1.10.0
      api_version: 1
  verifier:
    Pester:
      class: Kitchen::Verifier::Pester
      version: 0.7.1
      api_version: 1
loader:
  process_erb: true
  process_local: true
  process_global: true
  global_config:
  project_config:
    filename: C:/ProjectsGit/Hubot/.kitchen.yml
    raw_data:
      driver:
        name: vagrant
        communicator: winrm
        gui: true
      transport:
        name: winrm
      provisioner:
        name: dsc
        dsc_local_configuration_manager_version: wmf5
        dsc_local_configuration_manager:
          reboot_if_needed: true
          debug_mode: none
          allow_module_overwrite: true
        configuration_script_folder: examples
        configuration_script: dsc_configuration.ps1
        configuration_data_variable: configData
        configuration_name: Hubot
        modules_path: "."
        modules_from_gallery:
        - cChoco
        - xPSDesiredStateConfiguration
      platforms:
      - name: Win2016TP5Core
        transport:
          name: winrm
        provisioner:
          dsc_local_configuration_manager_version: wmf5
        driver_config:
          box: MattHodge/Win2016TP5Core
      verifier:
        name: pester
        test_folder: Tests
      suites:
      - name: default
  local_config:
  combined_config:
    filename:
    raw_data:
      driver:
        name: vagrant
        communicator: winrm
        gui: true
      transport:
        name: winrm
      provisioner:
        name: dsc
        dsc_local_configuration_manager_version: wmf5
        dsc_local_configuration_manager:
          reboot_if_needed: true
          debug_mode: none
          allow_module_overwrite: true
        configuration_script_folder: examples
        configuration_script: dsc_configuration.ps1
        configuration_data_variable: configData
        configuration_name: Hubot
        modules_path: "."
        modules_from_gallery:
        - cChoco
        - xPSDesiredStateConfiguration
      platforms:
      - name: Win2016TP5Core
        transport:
          name: winrm
        provisioner:
          dsc_local_configuration_manager_version: wmf5
        driver_config:
          box: MattHodge/Win2016TP5Core
      verifier:
        name: pester
        test_folder: Tests
      suites:
      - name: default
instances:
  default-Win2016TP5Core:
    platform:
      os_type: windows
      shell_type: powershell
    state_file:
      hostname: 127.0.0.1
      last_action: create
      password: vagrant
      port: '55985'
      rdp_port: '3389'
      username: vagrant
    driver:
      boot_timeout:
      box: MattHodge/Win2016TP5Core
      box_check_update:
      box_download_insecure:
      box_url:
      box_version:
      communicator: winrm
      customize: {}
      gui: true
      kitchen_root: C:/ProjectsGit/Hubot
      linked_clone:
      log_level: :info
      name: vagrant
      network: []
      pre_create_command:
      provider: virtualbox
      provision: false
      ssh: {}
      synced_folders: []
      test_base_path: C:/ProjectsGit/Hubot/test/integration
      vagrant_binary: vagrant
      vagrantfile_erb: C:/Users/myuser/AppData/Local/chefdk/gem/ruby/2.1.0/gems/kitchen-vagrant-0.20.0/templates/Vagrantfile.erb
      vagrantfiles: []
      vm_hostname:
    provisioner:
      command_prefix:
      configuration_data:
      configuration_data_variable: configData
      configuration_name: Hubot
      configuration_script: dsc_configuration.ps1
      configuration_script_folder: examples
      dsc_local_configuration_manager:
        reboot_if_needed: true
        debug_mode: none
        allow_module_overwrite: true
      dsc_local_configuration_manager_version: wmf5
      ftp_proxy:
      gallery_name:
      gallery_uri:
      http_proxy:
      https_proxy:
      kitchen_root: C:/ProjectsGit/Hubot
      max_retries: 1
      modules_from_gallery:
      - cChoco
      - xPSDesiredStateConfiguration
      modules_path: "."
      name: dsc
      nuget_force_bootstrap: true
      retry_on_exit_code: []
      root_path: "$env:TEMP\\kitchen"
      sudo:
      sudo_command:
      test_base_path: C:/ProjectsGit/Hubot/test/integration
      wait_for_retry: 30
    transport:
      connection_retries: 5
      connection_retry_sleep: 1
      elevated: false
      endpoint_template: http://%{hostname}:%{port}/wsman
      kitchen_root: C:/ProjectsGit/Hubot
      log_level: :info
      max_wait_until_ready: 600
      name: winrm
      password:
      port: 5985
      rdp_port: 3389
      test_base_path: C:/ProjectsGit/Hubot/test/integration
      username: administrator
      winrm_transport: :negotiate
    verifier:
      chef_omnibus_root: "/opt/chef"
      command_prefix:
      ftp_proxy:
      http_proxy:
      https_proxy:
      kitchen_root: C:/ProjectsGit/Hubot
      log_level: :info
      name: pester
      restart_winrm: false
      root_path: "$env:TEMP\\verifier"
      run_as_scheduled_task: false
      sudo:
      sudo_command:
      suite_name: default
      test_base_path: C:/ProjectsGit/Hubot/test/integration
      test_folder: Tests
      use_local_pester_module: false
```

.kitchen.yml
```yaml
---
driver:
  name: vagrant
  communicator: winrm
  gui: true

transport:
  name: winrm

provisioner:
    name: dsc
    dsc_local_configuration_manager_version: wmf5
    dsc_local_configuration_manager:
      reboot_if_needed: true
      debug_mode: none
      allow_module_overwrite: true
    configuration_script_folder: examples
    configuration_script: dsc_configuration.ps1
    configuration_data_variable: configData
    configuration_name: Hubot
    modules_path: .
    modules_from_gallery:
      - cChoco
      - xPSDesiredStateConfiguration

platforms:
- name: Win2016TP5Core
  transport:
    name: winrm
  provisioner:
    dsc_local_configuration_manager_version: wmf5
  driver_config:
    box: MattHodge/Win2016TP5Core

verifier:
  name: pester
  test_folder: Tests

suites:
  - name: default
```

Running with Vagrant version `Vagrant 1.8.4` and the following plugins:
```
winrm-fs (0.3.2)
vagrant-berkshelf (4.1.0)
vagrant-dsc (1.0.7)
vagrant-omnibus (1.4.1)
vagrant-reload (0.0.1)
vagrant-share (1.1.5, system)
vagrant-vbguest (0.12.0)
vagrant-vbox-snapshot (0.0.10)
vagrant-winrm (0.7.0)
```
