### ISSUE TITLE
WinRM error during verification stage when a converge reboots

### ISSUE THREAD

**Issue by PrahlM93** [test-kitchen/kitchen-dsc#22]
Using the latest kitchen-dsc and test-kitchen, I am getting an error when I run "kitchen test" on a converge that requires a reboot. Once the converge completes, the verification with Pester fails when trying to use the existing WinRM session.

Here is the relevant debug output:
```
-----> Setting up <companySplunkInstall-win2012r2-vsphere>...
       Finished setting up <companySplunkInstall-win2012r2-vsphere> (0m0.00s).
-----> Verifying <companySplunkInstall-win2012r2-vsphere>...
       Preparing files for transfer
D      Creating local sandbox in C:/Users/username/AppData/Local/Temp/companySplunkInstall-win2012r2-vsphere-sandbox-20160621-6904-oabvso
       Preparing to copy supporting powershell modules.
       Preparing to copy files from C:/Users/username/Documents/companyresources/test/integration/companySplunkInstall to the SUT.
D      Copying C:/Users/username/Documents/companyresources/test/integration/companySplunkInstall/companySplunkInstall.Tests.ps1 to C:/Users/username/AppData/Local/Temp/companySplunkInstall-win2012r2-vsphere-sandbox-20160621-6904-oabvso/companySplunkInstall.Tests.ps1
D      [WinRM] reusing existing connection negotiate::http://192.168.1.2:5985/wsman<{:user=>"vagrant", :pass=>"vagrant", :elevated_username=>"vagrant", :elevated_password=>"vagrant", :no_ssl_peer_verification=>true, :disable_sspi=>false, :basic_auth_only=>false}>
D      [WinRM] negotiate::http://192.168.1.2:5985/wsman<{:user=>"vagrant", :pass=>"vagrant", :elevated_username=>"vagrant", :elevated_password=>"vagrant", :no_ssl_peer_verification=>true, :disable_sspi=>false, :basic_auth_only=>false}> (set-executionpolicy unrestricted -force;
$global:ProgressPreference = 'SilentlyContinue'
$VerbosePreference = 'Continue'
$env:psmodulepath += ";$(join-path (resolve-path $env:temp).path 'verifier/modules')";
# $env:psmodulepath -split ';' | % {write-output "PSModulePath contains:"} {write-output "`t$_"}
        function directory($path){
if (test-path $path) {(resolve-path $path).providerpath}
else {(resolve-path (mkdir $path)).providerpath}
        }
        $VerifierModulePath = directory $env:temp/verifier/modules
        $VerifierTestsPath = directory $env:temp/verifier/pester

        function test-module($module){
(get-module $module -list) -ne $null
        }
        if (-not (test-module pester)) {
if (test-module PowerShellGet){
  import-module PowerShellGet -force
  import-module PackageManagement -force
  get-packageprovider -name NuGet -force | out-null
  install-module Pester -force
}
else {
  if (-not (test-module PsGet)){
    iex (new-object Net.WebClient).DownloadString('http://bit.ly/GetPsGet')
  }
  try {
    import-module psget -force -erroraction stop
    Install-Module Pester
  }
  catch {
    Write-Output "Installing from Github"
    $zipfile = join-path(resolve-path "$env:temp/verifier") "pester.zip"
    if (-not (test-path $zipfile)){
      $source = 'https://github.com/pester/Pester/archive/3.3.14.zip'
      [byte[]]$bytes = (new-object System.net.WebClient).DownloadData($source)
      [IO.File]::WriteAllBytes($zipfile, $bytes)
      $bytes = $null
      [gc]::collect()
      write-output "Downloaded Pester.zip"
    }
    write-output "Creating Shell.Application COM object"
    $shellcom = new-object -com shell.application
    Write-Output "Creating COM object for zip file."
    $zipcomobject = $shellcom.namespace($zipfile)
    Write-Output "Creating COM object for module destination."
    $destination = $shellcom.namespace($VerifierModulePath)
    Write-Output "Unpacking zip file."
    $destination.CopyHere($zipcomobject.Items(), 0x610)
    rename-item (join-path $VerifierModulePath "Pester-3.3.14") -newname 'Pester' -force
  }
}
        }
        if (-not (test-module Pester)) {
throw "Unable to install Pester.  Please include Pester in your base image or install during your converge."
        }

)
$$$$$$ #< CLIXML
$$$$$$ <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><S S="verbose">Populating RepositorySourceLocation property for module Pester.</S><S S="verbose">Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0\Pester.psm1'.</S><S S="verbose">Populating RepositorySourceLocation property for module Pester.</S><S S="verbose">Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0\Pester.psm1'.</S></Objs>
       Transferring files to <companySplunkInstall-win2012r2-vsphere>
D      creating hash for file $env:TEMP\verifier
D      creating hash for directory $env:TEMP\verifier
D      Populating files
D      +++ Adding NamedPipes/NamedPipes.psm1
D      +++ Adding PesterUtil/PesterUtil.psm1
D      +++ Adding ScheduledTaskRunner/ScheduledTaskRunner.psm1
D      === All files added.
D      Running check_files.ps1
D      @{
D        "d42c205f5954942e1355b2f476f3227b" = @{
D          "target" = "$env:TEMP\verifier";
D          "src_basename" = "companySplunkInstall.Tests.ps1";
D          "dst" = "$env:TEMP\verifier"
D        };
D        "deec30762f4c7639a4f2dcb36f57d24c" = @{
D          "target" = "$env:TEMP\winrm-upload\tmpzip-deec30762f4c7639a4f2dcb36f57d24c.zip";
D          "src_basename" = "modules";
D          "dst" = "$env:TEMP\verifier\modules"
D        }
D      }
D      Cleaning up local sandbox in C:/Users/username/AppData/Local/Temp/companySplunkInstall-win2012r2-vsphere-sandbox-20160621-6904-oabvso
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [WinRM::CommandExecutor#open must be called before any run methods are invoked] on companySplunkInstall-win2012r2-vsphere
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [WinRM::CommandExecutor#open must be called before any run methods are invoked] on companySplunkInstall-win2012r2-vsphere
D      ----------------------
D      ------Backtrace-------
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/command.rb:187:in `report_errors'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/command.rb:178:in `run_action'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/command/test.rb:45:in `block in call'
D      C:/opscode/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/command/test.rb:41:in `call'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/cli.rb:56:in `perform'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/cli.rb:231:in `test'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/cli.rb:325:in `invoke_task'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/bin/kitchen:13:in `block in <top (required)>'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/errors.rb:174:in `with_friendly_errors'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/bin/kitchen:13:in `<top (required)>'
D      C:/opscode/chefdk/bin/kitchen:20:in `load'
D      C:/opscode/chefdk/bin/kitchen:20:in `<main>'
D      ----End Backtrace-----
D      -Composite Exception--
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #verify action: [WinRM::CommandExecutor#open must be called before any run methods are invoked] on companySplunkInstall-win2012r2-vsphere
D      ----------------------
D      ------Backtrace-------
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/winrm-1.8.1/lib/winrm/command_executor.rb:180:in `ensure_open_shell!'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/winrm-1.8.1/lib/winrm/command_executor.rb:92:in `run_cmd'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/winrm-fs-0.4.2/lib/winrm-fs/core/file_transporter.rb:448:in `stream_upload'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/winrm-fs-0.4.2/lib/winrm-fs/core/file_transporter.rb:249:in `block in create_remote_hash_file'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/winrm-fs-0.4.2/lib/winrm-fs/core/file_transporter.rb:249:in `open'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/winrm-fs-0.4.2/lib/winrm-fs/core/file_transporter.rb:249:in `create_remote_hash_file'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/winrm-fs-0.4.2/lib/winrm-fs/core/file_transporter.rb:201:in `check_files'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/winrm-fs-0.4.2/lib/winrm-fs/core/file_transporter.rb:80:in `block in upload'
D      C:/opscode/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/winrm-fs-0.4.2/lib/winrm-fs/core/file_transporter.rb:78:in `upload'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/transport/winrm.rb:132:in `upload'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/verifier/base.rb:77:in `block in call'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/transport/winrm.rb:524:in `reuse_connection'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/transport/winrm.rb:72:in `connection'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/verifier/base.rb:73:in `call'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:423:in `block in verify_action'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:513:in `call'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:513:in `synchronize_or_call'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:478:in `block in action'
D      C:/opscode/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:477:in `action'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:415:in `verify_action'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:348:in `block in transition_to'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:347:in `each'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:347:in `transition_to'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:160:in `verify'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:189:in `block in test'
D      C:/opscode/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:185:in `test'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/command.rb:201:in `public_send'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/command.rb:201:in `run_action_in_thread'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/command.rb:173:in `block (2 levels) in run_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:450:in `call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:450:in `block in create_with_logging_context'
D      ----End Backtrace-----
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #verify action: [WinRM::CommandExecutor#open must be called before any run methods are invoked]
D      ----------------------
D      ------Backtrace-------
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/winrm-1.8.1/lib/winrm/command_executor.rb:180:in `ensure_open_shell!'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/winrm-1.8.1/lib/winrm/command_executor.rb:92:in `run_cmd'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/winrm-fs-0.4.2/lib/winrm-fs/core/file_transporter.rb:448:in `stream_upload'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/winrm-fs-0.4.2/lib/winrm-fs/core/file_transporter.rb:249:in `block in create_remote_hash_file'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/winrm-fs-0.4.2/lib/winrm-fs/core/file_transporter.rb:249:in `open'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/winrm-fs-0.4.2/lib/winrm-fs/core/file_transporter.rb:249:in `create_remote_hash_file'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/winrm-fs-0.4.2/lib/winrm-fs/core/file_transporter.rb:201:in `check_files'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/winrm-fs-0.4.2/lib/winrm-fs/core/file_transporter.rb:80:in `block in upload'
D      C:/opscode/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/winrm-fs-0.4.2/lib/winrm-fs/core/file_transporter.rb:78:in `upload'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/transport/winrm.rb:132:in `upload'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/verifier/base.rb:77:in `block in call'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/transport/winrm.rb:524:in `reuse_connection'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/transport/winrm.rb:72:in `connection'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/verifier/base.rb:73:in `call'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:423:in `block in verify_action'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:513:in `call'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:513:in `synchronize_or_call'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:478:in `block in action'
D      C:/opscode/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:477:in `action'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:415:in `verify_action'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:348:in `block in transition_to'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:347:in `each'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:347:in `transition_to'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:160:in `verify'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:189:in `block in test'
D      C:/opscode/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/instance.rb:185:in `test'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/command.rb:201:in `public_send'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/command.rb:201:in `run_action_in_thread'
D      C:/Users/username/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.10.0/lib/kitchen/command.rb:173:in `block (2 levels) in run_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:450:in `call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:450:in `block in create_with_logging_context'
D      ----End Backtrace-----
D      [WinRM] closing remote shell 6CED209D-ED19-4114-8316-AA615DE8C822 on http://192.168.1.2:5985/wsman
D      [WinRM] remote shell 6CED209D-ED19-4114-8316-AA615DE8C822 closed
```

**Comment by mwrock** [comment]
heh. I JUST released a fix in winrm-fs 0.4.3. Try updating to that gem.

**Comment by mwrock** [comment]
see #20

**Comment by PrahlM93** [comment]
@mwrock, I'm using chefdk, and I'm wondering how I can make test-kitchen use the latest version of winrm-fs that I installed.

Thanks for the help.

**Comment by mwrock** [comment]
`chef gem install winrm-fs` should do the trick

**Comment by PrahlM93** [comment]
@mwrock, I'm getting the same error, and kitchen-pester is using winrm-fs 0.4.3.

**Comment by mwrock** [comment]
yes this does look like a separate issue.

**Comment by smurawski** [comment]
@PrahlM93 after you get through the converge, can you tell if any of the test files get copied?  `kitchen exec -c 'dir $env:temp/verifier/'` should get the relevant info.

**Comment by smurawski** [comment]
@PrahlM93 Also, a gist of `kitchen diagnose` would help.

**Comment by PrahlM93** [comment]
@smurawski, here are the results from the kitchen exec.
```
PS C:\Users\username\Documents\companyresources> kitchen exec -c 'dir $env:temp/verifier/' companySplunkInstall-win2012r2-vsphere
-----> Execute command on companySplunkInstall-win2012r2-vsphere.


           Directory: C:\Users\vagrant\AppData\Local\Temp\verifier


       Mode                LastWriteTime         Length Name
       ----                -------------         ------ ----
       d-----        6/21/2016   3:34 PM                modules
       d-----        6/21/2016   3:34 PM                pester

```

**Comment by smurawski** [comment]
@PrahlM93 are you using the "restart_winrm" setting?

**Comment by PrahlM93** [comment]
@smurawski, I haven't been but I just tried it and I got the same error.

**Comment by smurawski** [comment]
@PrahlM93 using that would potentially cause that error - which is why I asked.

Can you share the result of a `kitchen diagnose`?  kitchen-pester doesn't really do anything with the transport directly, so I'm not sure what is causing the shell to close unexpectedly.  

For the reboot by DSC, are you letting kitchen-dsc do the reboot or are you letting the LCM do it?

**Comment by PrahlM93** [comment]
@smurawski, I am letting kitchen-dsc do the reboot, which it does quite well. Thank you for adding that feature in!

Here's a snippet of the kitchen diagnose
```
    provisioner:
      command_prefix:
      configuration_data:
      configuration_data_variable: ConfigData
      configuration_name: companySplunkInstall
      configuration_script: Test_Kitchen_DSC_Configuration.ps1
      configuration_script_folder: examples
      dsc_local_configuration_manager:
        action_after_reboot: ContinueConfiguration
        allow_module_overwrite: false
        certificate_id: 29010115C9C0C0B2C9272617DBAF161763FF2D7E
        configuration_mode: ApplyOnly
        configuration_mode_frequency_mins: 30
        debug_mode: None
        reboot_if_needed: false
        refresh_frequency_mins: 30
        refresh_mode: PUSH
      dsc_local_configuration_manager_version: wmf5
      ftp_proxy:
      gallery_name: CompanyNuget
      gallery_uri:
      http_proxy:
      https_proxy:
      kitchen_root: C:/Users/username/Documents/companyresources
      max_retries: 1
      modules_from_gallery:
      - name: xPSDesiredStateConfiguration
        requiredversion: 3.9.0.0
      modules_path: modules
      name: dsc
      nuget_force_bootstrap: true
      retry_on_exit_code: []
      root_path: "$env:TEMP\\kitchen"
      sudo:
      sudo_command:
      test_base_path: C:/Users/username/Documents/companyresources/test/integration
      wait_for_retry: 30
    transport:
      connection_retries: 5
      connection_retry_sleep: 1
      elevated: false
      endpoint_template: http://%{hostname}:%{port}/wsman
      kitchen_root: C:/Users/username/Documents/companyresources
      log_level: :info
      max_wait_until_ready: 600
      name: winrm
      password:
      port: 5985
      rdp_port: 3389
      test_base_path: C:/Users/username/Documents/companyresources/test/integration
      username: administrator
      winrm_transport: :negotiate
    verifier:
      chef_omnibus_root: "/opt/chef"
      command_prefix:
      ftp_proxy:
      http_proxy:
      https_proxy:
      kitchen_root: C:/Users/username/Documents/companyresources
      log_level: :info
      name: pester
      restart_winrm: false
      root_path: "$env:TEMP\\verifier"
      run_as_scheduled_task: false
      sudo:
      sudo_command:
      suite_name: companySplunkInstall
      test_base_path: C:/Users/username/Documents/companyresources/test/integration
      test_folder:
      use_local_pester_module: false
```
