### ISSUE TITLE
Ability to run multiple dsc configurations

### ISSUE THREAD

**Issue by TraGicCode** [test-kitchen/kitchen-dsc#32]
It would be nice to be able to test the absense of resources with the dsc provisioner. 

For Example:
I have a dsc resource that creates an iis website.  I would like to verify that passing "Absent" for Ensure on my resource actually removes the website. Instead of creating an image with iis and the expected website already created i would like the ability to run multiple dsc configurations in order to

1.) Setup the system under test
2.) Converge the system under test

One way of doing this would be to allow the ability to pass an array of dsc configurations to the provisioner and it would run them in the specified order.

An example might look like this:
```
suites:
  - name: MSFT_xWinRMListener
    provisioner: 
      configuration_script_folder: Tests/Integration/MSFT_xWinRMListener
      configuration_script: MSFT_xWinRMListener.config.ps1
      configuration_name:
        - CreateHttpListener
        - RemoveHttpListener
```
